# Logrotate configuration for TInstaller logs
/opt/web-serv/logs/server.log /opt/web-serv/logs/server.out /opt/web-serv/logs/update.log {
    size 5M
    rotate 3
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
}
